
#include <stubhlp.h>

STUB(auxGetDevCapsA)
STUB(auxGetNumDevs)
STUB(auxGetVolume)
STUB(auxSetVolume)

STUB(mciSendCommandA)
STUB(mciSendStringA)

STUB(midiOutClose)
STUB(midiOutLongMsg)
STUB(midiOutOpen)
STUB(midiOutPrepareHeader)
STUB(midiOutReset)
STUB(midiOutShortMsg)
STUB(midiOutUnprepareHeader)

STUB(mixerClose)
STUB(mixerGetControlDetailsA)
STUB(mixerGetLineControlsA)
STUB(mixerGetLineInfoA)
STUB(mixerGetNumDevs)
STUB(mixerOpen)
STUB(mixerSetControlDetails)

//STUB(timeBeginPeriod)
//STUB(timeEndPeriod)
//STUB(timeGetTime)
STUB(timeKillEvent)
STUB(timeSetEvent)

STUB(waveOutClose)
//STUB(waveOutGetDevCapsA)
//STUB(waveOutGetID)
//STUB(waveOutOpen)
//STUB(waveOutPrepareHeader)
//STUB(waveOutReset)
STUB(waveOutSetVolume)
//STUB(waveOutUnprepareHeader)
//STUB(waveOutWrite)

STUB(waveInAddBuffer)
STUB(waveInClose)
STUB(waveInOpen)
STUB(waveInPrepareHeader)
STUB(waveInReset)
STUB(waveInStart)
STUB(waveInUnprepareHeader)
