
#include <stubhlp.h>

STUB(BitBlt)
STUB(CreateCompatibleBitmap)
STUB(CreateCompatibleDC)
STUB(CreatePalette)
STUB(DeleteDC)
STUB(DeleteObject)
//STUB(GdiSetBatchLimit)
STUB(GetDIBits)
STUB(GetPixel)
STUB(GetSystemPaletteEntries)
STUB(GetSystemPaletteUse)
STUB(PatBlt)
STUB(RealizePalette)
STUB(SelectObject)
STUB(SelectPalette)
STUB(SetPixel)
STUB(SetStretchBltMode)
STUB(StretchBlt)
STUB(StretchDIBits)
